name: Supabase - Deploy Edge Function

on:
  push:
    paths:
      - ".github/workflows/supabase-deploy-function.yml"
      - "supabase/functions/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npx supabase functions deploy notify --project-ref mitawjpdxkheascdiffz
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      - run: npx supabase functions deploy resolve-automation --project-ref mitawjpdxkheascdiffz
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
